"""Batch translate all Chinese text to English across all Python files."""
import os
import re

BASE = os.path.dirname(os.path.abspath(__file__))

def translate_file(filepath, replacements):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  Translated: {os.path.relpath(filepath, BASE)}")

def main():
    # ===== match_agent/match_agent.py =====
    translate_file(os.path.join(BASE, "match_agent", "match_agent.py"), [
        ('TASK_LOAN: "贷款决策"', 'TASK_LOAN: "Loan Decision"'),
        ('TASK_EMPLOYMENT: "就业决策"', 'TASK_EMPLOYMENT: "Employment Decision"'),
        ('TASK_CONSUMPTION: "消费决策"', 'TASK_CONSUMPTION: "Consumption Decision"'),
        ('TASK_STOCK: "股票决策"', 'TASK_STOCK: "Stock Decision"'),
        ('TASK_DEPOSIT: "存款决策"', 'TASK_DEPOSIT: "Deposit Decision"'),
        ('TASK_LOAN: "商业银行"', 'TASK_LOAN: "Commercial Bank"'),
        ('TASK_EMPLOYMENT: "人才市场"', 'TASK_EMPLOYMENT: "Job Market"'),
        ('TASK_CONSUMPTION: "超市"', 'TASK_CONSUMPTION: "Supermarket"'),
        ('TASK_STOCK: "证券交易所"', 'TASK_STOCK: "Stock Exchange"'),
        ('TASK_DEPOSIT: "商业银行"', 'TASK_DEPOSIT: "Commercial Bank"'),
        ('f"找不到 households.json：{households_path}\\n"', 'f"households.json not found: {households_path}\\n"'),
        ('"请先运行仿真生成结果，或用 --households 指定正确路径。"', '"Please run the simulation first, or specify the correct path with --households."'),
        ('f"tick 必须在 1..{NUM_TICKS} 之间，收到 {selected_tick}"', 'f"tick must be between 1..{NUM_TICKS}, got {selected_tick}"'),
        ('f"该 agent 没有 tick={tick_0based} 的记录"', 'f"This agent has no record for tick={tick_0based}"'),
        ('f"wealth_level 必须是 1..5，收到 {wealth_level}"', 'f"wealth_level must be 1..5, got {wealth_level}"'),
        ('f"risk_preference 必须是 {list(RISK_ORDER)} 之一，收到 {risk_preference!r}"', 'f"risk_preference must be one of {list(RISK_ORDER)}, got {risk_preference!r}"'),
        ("'劳动力' if is_labor_force else '非劳动力'", "'labor force' if is_labor_force else 'non-labor force'"),
        ('f"财富档={wealth_level} 没有任何候选 agent。"', 'f"wealth_level={wealth_level}: no candidate agents found."'),
        ('"tick {selected_tick}、身份={', '"tick {selected_tick}, identity={'),
        ('}、\\n"', '}, "'),
        ('("1", "true", "t", "yes", "y", "labor", "劳动力")', '("1", "true", "t", "yes", "y", "labor")'),
        ('description="玩家 → Agent 匹配（Economic World Model 游戏交互）"', 'description="Player-Agent matching (Economic World Model game interaction)"'),
        ('help="玩家选择的 tick (1-13)"', 'help="Player selected tick (1-13)"'),
        ('help="身份：true=劳动力 / false=非劳动力"', 'help="Identity: true=labor force / false=non-labor force"'),
        ('help="财富档 (1-5)"', 'help="Wealth level (1-5)"'),
        ('help="风险偏好"', 'help="Risk preference"'),
        ('help=f"households.json 路径（默认 {DEFAULT_HOUSEHOLDS_PATH}）"', 'help=f"households.json path (default: {DEFAULT_HOUSEHOLDS_PATH})"'),
        ('help=f"玩家 JSON 输出目录（默认 {DEFAULT_PLAYER_DIR}）"', 'help=f"Player JSON output directory (default: {DEFAULT_PLAYER_DIR})"'),
        ('help=f"玩家 JSON 文件名（默认 {DEFAULT_PLAYER_FILENAME}）"', 'help=f"Player JSON filename (default: {DEFAULT_PLAYER_FILENAME})"'),
        ('print("  匹配结果")', 'print("  Match Result")'),
        ("f\"身份={'劳动力' if player['is_labor_force'] else '非劳动力'}, \"", "f\"identity={'labor force' if player['is_labor_force'] else 'non-labor force'}, \""),
        ("f\"财富档={player['wealth_level']}, 风险={player['risk_preference']}\"", "f\"wealth_level={player['wealth_level']}, risk={player['risk_preference']}\""),
        ('f"  选择：tick={player[\'selected_tick\']}, "', 'f"  Selection: tick={player[\'selected_tick\']}, "'),
        ('f"  匹配到 agent_id = {player[\'matched_agent_id\']}"', 'f"  Matched agent_id = {player[\'matched_agent_id\']}"'),
        ("f\"  agent 风险偏好 = {player['matched_risk']} \"", "f\"  Agent risk preference = {player['matched_risk']} \""),
        ("f\"(距离 {player['risk_distance']}, \"", "f\"(distance {player['risk_distance']}, \""),
        ("f\"{'精确命中' if player['exact_risk_match'] else '最近匹配'})\"", "f\"{'exact match' if player['exact_risk_match'] else 'nearest match'})\""),
        ('f"  可执行任务（{len(player[\'available_tasks\'])} 项）：{task_str}"', 'f"  Available tasks ({len(player[\'available_tasks\'])}): {task_str}"'),
        ('f"找不到 information_environment.json：{env_path}"', 'f"information_environment.json not found: {env_path}"'),
        ('f"环境数据没有 tick={tick_0based} 的记录"', 'f"Environment data has no record for tick={tick_0based}"'),
        ('f"  ✅ 玩家 JSON 已写入：{player[\'_player_json_path\']}"', 'f"  Player JSON written to: {player[\'_player_json_path\']}"'),
    ])

    # ===== EPTI/judge_epti.py =====
    translate_file(os.path.join(BASE, "EPTI", "judge_epti.py"), [
        ('"时间偏好"', '"Time Preference"'),
        ('"消费"', '"Spending"'),
        ('"储蓄"', '"Saving"'),
        ('"风险态度"', '"Risk Attitude"'),
        ('"激进"', '"Aggressive"'),
        ('"保守"', '"Conservative"'),
        ('"市场立场"', '"Market Stance"'),
        ('"逆势"', '"Contrarian"'),
        ('"顺势"', '"Trend-following"'),
        ('"消费品味"', '"Consumption Taste"'),
        ('"实用"', '"Practical"'),
        ('"精致"', '"Refined"'),
        ('"花钱大方，倾向即时享受，储蓄意愿低"', '"Spends freely, prefers instant gratification, low savings inclination"'),
        ('"花钱节制，倾向延迟满足，储蓄意愿高"', '"Spends conservatively, prefers delayed gratification, high savings inclination"'),
        ('"大胆冒险，能接受波动，追求高回报"', '"Bold risk-taker, tolerates volatility, pursues high returns"'),
        ('"谨慎保守，厌恶波动，宁可少赚不亏"', '"Cautious and conservative, dislikes volatility, prefers safety over returns"'),
        ('"逆势而行，别人恐惧我贪婪，喜欢抄底"', '"Goes against the trend, greedy when others are fearful, likes buying dips"'),
        ('"顺势而为，跟随市场方向，别人买我也买"', '"Follows the trend, moves with the market, buys when others buy"'),
        ('"注重实用，日用品比重高，对奢侈品兴趣低"', '"Values practicality, high proportion of necessities, low interest in luxury"'),
        ('"追求精致，奢侈品比重高，愿意为品质多花钱"', '"Pursues refinement, high proportion of luxury goods, willing to pay more for quality"'),
        ('"持平(0)"', '"neutral(0)"'),
        ('"意愿消费比例"', '"desired consumption ratio"'),
        ('"权重2"', '"weight2"'),
        ('"意愿贷款比例"', '"desired loan ratio"'),
        ('"意愿股票投资比例"', '"desired stock investment ratio"'),
        ('"意愿存款利率偏离"', '"desired deposit rate deviation"'),
        ('"消费中必需品占比"', '"necessity share in consumption"'),
        ('"意愿工资偏离"', '"desired wage deviation"'),
        ('"↑高于初期"', '"above initial"'),
        ('"↓低于初期"', '"below initial"'),
        ('"=持平"', '"=neutral"'),
        ('f"玩家 EPTI 类型：{epti}"', 'f"Player EPTI type: {epti}"'),
        ('"对照同组别"', '"Comparison group"'),
        ('"劳动力"', '"labor force"'),
        ('"非劳动力"', '"non-labor force"'),
        ('"财富档"', '"wealth level"'),
    ])

    # ===== stock/stock_briefing.py =====
    translate_file(os.path.join(BASE, "stock", "stock_briefing.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('"conservative": "保守谨慎"', '"conservative": "conservative and cautious"'),
        ('"steady": "稳健务实"', '"steady": "steady and practical"'),
        ('"balanced": "攻守平衡"', '"balanced": "balanced"'),
        ('"growth": "积极进取"', '"growth": "growth-oriented"'),
        ('"aggressive": "大胆激进"', '"aggressive": "bold and aggressive"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('f"{x:,.2f} 元"', 'f"{x:,.2f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"（你这个角色没有股票决策任务。）"', '"(Your character does not have a stock decision task.)"'),
        ('"【证券交易所】"', '"[Stock Exchange]"'),
        ('"（经纪人调出你的账户）"', '"(The broker pulls up your account)"'),
        ('"「来啦！看看今天怎么投。」"', '"Let me see how to invest today."'),
        ("f\"「你的情况——**家底{WEALTH_PLAIN.get(wealth, '不上不下')}**，**性格{RISK_PLAIN.get(risk, '平衡')}**，\"", "f\"Your situation: **wealth: {WEALTH_PLAIN.get(wealth, 'average')}**, **personality: {RISK_PLAIN.get(risk, 'balanced')}**, \""),
        ('f"**能力{_beta_plain(beta)}档**（同样出价，能力强的人先成交）。"', 'f"**ability: {_beta_plain(beta)} tier** (at the same bid price, those with stronger ability get matched first). "'),
        ('f"你现在**持有 {sh_nec} 股生产日用品的公司的股票、"', 'f"You currently **hold {sh_nec} shares of the necessity goods company and "'),
        ('f"{sh_lux} 股生产高档货的公司的股票**。"', 'f"{sh_lux} shares of the luxury goods company**. "'),
        ("f\"上次你拿了 {last_ratio*100:.0f}% 的闲钱炒股，\"", "f\"Last time you invested {last_ratio*100:.0f}% of your spare cash in stocks, \""),
        ("f\"{'六成多' if last_nec_share > 0.55 else '大约一半' if last_nec_share > 0.45 else '少部分'}买的日用品那家。\"", "f\"{'mostly' if last_nec_share > 0.55 else 'about half' if last_nec_share > 0.45 else 'a small portion'} in the necessity goods company. \""),
        ('f"这次你能拿来投的**闲钱大约 {_money(remaining)}**。」"', 'f"This time your **available spare cash is about {_money(remaining)}**."'),
        ('"「注意！你这个月借了钱，按规矩**闲钱得全部投进股市**，不用选比例了。」"', '"Note! You borrowed money this month, so by the rules **all spare cash must be invested in stocks** - no need to choose a ratio."'),
        ('"不好说"', '"hard to say"'),
        ('"不错"', '"good"'),
        ('"还行"', '"decent"'),
        ('"一般般"', '"mediocre"'),
        ('f"12 家里排第 {rk_nec}"', 'f"ranked {rk_nec} out of 12"'),
        ('"排名未知"', '"ranking unknown"'),
        ('f"排第 {rk_lux}"', 'f"ranked {rk_lux}"'),
        ("f\"「行情——上一轮日用品公司股价 **{_price(p_nec)}**，高档货公司 **{_price(p_lux)}**。\"", "f\"Market info: last round necessity company stock price **{_price(p_nec)}**, luxury company **{_price(p_lux)}**. \""),
        ("f\"**日用品公司赚钱能力{_rank_eval(rk_nec)}，{rk_nec_str}；高档货公司{rk_lux_str}，{_rank_eval(rk_lux)}**。\"", "f\"**Necessity company profitability: {_rank_eval(rk_nec)}, {rk_nec_str}; luxury company: {rk_lux_str}, {_rank_eval(rk_lux)}**. \""),
        ('f"**{CN_ECONOMIC_BACKGROUND.get(tick0, \'\')}**」"', 'f"**{CN_ECONOMIC_BACKGROUND.get(tick0, \'\')}**"'),
        ('"「三个决定：① 日用品公司股票最多出多少钱买？② 高档货公司呢？"', '"Three decisions: 1. What is the max price you would pay for necessity company stock? 2. What about luxury company? "'),
        ('"③ 两家怎么分配？提醒：**股市有摩擦，不一定全买得到**。」"', '"3. How to split between the two? Reminder: **the stock market has friction - you may not be able to buy everything**."'),
        ('"「四个决定：① 日用品公司股票最多出多少钱买？② 高档货公司呢？"', '"Four decisions: 1. What is the max price you would pay for necessity company stock? 2. What about luxury company? "'),
        ('"③ 拿多少比例的闲钱去投？④ 两家怎么分配？提醒：**股市有摩擦，不一定全买得到**。」"', '"3. What proportion of spare cash to invest? 4. How to split between the two? Reminder: **the stock market has friction - you may not be able to buy everything**."'),
        ('description="证券交易所 NPC 简报（股票决策）"', 'description="Stock Exchange NPC briefing (stock decision)"'),
    ])

    # ===== stock/apply_stock_decision.py =====
    translate_file(os.path.join(BASE, "stock", "apply_stock_decision.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('f"档位必须是 1~5，收到 {lv}"', 'f"Level must be 1~5, got {lv}"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有股票决策任务。"', '"This player has no stock decision task."'),
        ('f"stock_ratio_level 必须是 1~5，收到 {stock_ratio_level}"', 'f"stock_ratio_level must be 1~5, got {stock_ratio_level}"'),
        ('description="股票题 → 写回 player.json"', 'description="Stock decision -> write back to player.json"'),
        ('help="股票投资比例档位（贷款成功时忽略，可省略）"', 'help="Stock investment ratio level (ignored when loan approved, optional)"'),
        ('"（贷款成功，强制 100%）"', '" (loan approved, forced 100%)"'),
        ('f"日用品股愿价 {d[\'desired_stock_price_necessity\']} | 高档货股愿价 {d[\'desired_stock_price_luxury\']}"', 'f"Necessity stock bid {d[\'desired_stock_price_necessity\']} | Luxury stock bid {d[\'desired_stock_price_luxury\']}"'),
        ('f" | 投资比例 {d[\'stock_ratio\']*100:.1f}%{forced} | 日用品股占比 {d[\'necessity_stock_ratio\']*100:.1f}%"', 'f" | Investment ratio {d[\'stock_ratio\']*100:.1f}%{forced} | Necessity stock share {d[\'necessity_stock_ratio\']*100:.1f}%"'),
        ('f" | 总投资 {d[\'total_invest\']:,.0f} 元（已写回）"', 'f" | Total investment {d[\'total_invest\']:,.0f} yuan (written back)"'),
    ])

    # ===== stock/stock_market_clearing.py =====
    translate_file(os.path.join(BASE, "stock", "stock_market_clearing.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"该 agent 没有 tick={t0} 的记录"', 'f"This agent has no record for tick={t0}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('f"「{name}：以 {o[\'clearing_price\']:,.2f} 元买入 {q} 股，现持 {o[\'new_shares\']} 股。」"', 'f"{name}: bought {q} shares at {o[\'clearing_price\']:,.2f} yuan, now holding {o[\'new_shares\']} shares."'),
        ('f"「{name}：以 {o[\'clearing_price\']:,.2f} 元卖出 {-q} 股，现持 {o[\'new_shares\']} 股。」"', 'f"{name}: sold {-q} shares at {o[\'clearing_price\']:,.2f} yuan, now holding {o[\'new_shares\']} shares."'),
        ('f"「{name}：本次未成交（持仓不变 {o[\'new_shares\']} 股），出清价 {o[\'clearing_price\']:,.2f} 元。」"', 'f"{name}: no transaction this time (holdings unchanged at {o[\'new_shares\']} shares), clearing price {o[\'clearing_price\']:,.2f} yuan."'),
        ('"【股票市场 · 集合竞价结果】"', '"[Stock Market - Call Auction Results]"'),
        ('"（经纪人打印出成交回执）"', '"(The broker prints the transaction receipt)"'),
        ('_leg("日用品股", outcomes["necessity"])', '_leg("Necessity stock", outcomes["necessity"])'),
        ('_leg("高档货股", outcomes["luxury"])', '_leg("Luxury stock", outcomes["luxury"])'),
        ('f"「本次投资后您的持股总市值约 {total:,.0f} 元。」"', 'f"Your total stock holdings are now worth approximately {total:,.0f} yuan."'),
        ('f"「您还有约 {remaining:,.0f} 元现金留存，可以在下一步存进银行。」"', 'f"You still have about {remaining:,.0f} yuan in cash remaining, which you can deposit in the bank in the next step."'),
        ('"「资金基本都投进了股市，剩余现金所剩无几。」"', '"Most of your funds have been invested in stocks, very little cash remains."'),
        ('description="玩家股票市场撮合（写回 player.json）"', 'description="Player stock market matching (write back to player.json)"'),
    ])

    # ===== loan/loan_briefing.py =====
    translate_file(os.path.join(BASE, "loan", "loan_briefing.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('f"{x:,.2f} 元"', 'f"{x:,.2f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"央行刚加息了"', '"The central bank just raised interest rates"'),
        ('"（你这个角色这个月没有贷款资格，可以直接跳过银行，前往下一站。）"', '"(Your character is not eligible for a loan this month. You can skip the bank and proceed to the next stop.)"'),
    ])

    # ===== loan/loan_amount_dialogue.py =====
    translate_file(os.path.join(BASE, "loan", "loan_amount_dialogue.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"（你这个角色没有贷款资格，不会进入这段对话。）"', '"(Your character is not eligible for a loan and will not enter this dialogue.)"'),
        ('"当前行情利率"', '"current market rate"'),
    ])

    # ===== loan/apply_loan_decision.py =====
    translate_file(os.path.join(BASE, "loan", "apply_loan_decision.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"环境快照里缺少有效的 last_avg_bank_loan_rate"', '"Environment snapshot is missing a valid last_avg_bank_loan_rate"'),
        ('f"level 必须是 1~5，收到 {level}"', 'f"level must be 1~5, got {level}"'),
        ('"market_rate 必须为正"', '"market_rate must be positive"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有贷款资格"', '"This player is not eligible for a loan"'),
        ('"借"', '"borrow"'),
        ('"是"', '"yes"'),
        ('description="贷款决策两道题 → 更新参数写回 player.json"', 'description="Loan decision (two questions) -> update params and write back to player.json"'),
        ('f"利率预期档位 {d[\'level\']}"', 'f"Interest rate expectation level {d[\'level\']}"'),
        ('f" | 上月市场利率 {d[\'market_rate\']*100:.2f}%"', 'f" | Last month market rate {d[\'market_rate\']*100:.2f}%"'),
        ('f" → 意愿贷款利率 {d[\'desired_loan_rate\']*100:.2f}%"', 'f" -> Desired loan rate {d[\'desired_loan_rate\']*100:.2f}%"'),
        ("f\" | 是否借：{'是' if d['wants_loan'] else '否'}\"", "f\" | Borrow: {'yes' if d['wants_loan'] else 'no'}\""),
        ('"（贷款金额已置 0）"', '" (loan amount set to 0)"'),
    ])

    # ===== loan/apply_loan_amount.py =====
    translate_file(os.path.join(BASE, "loan", "apply_loan_amount.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"level 必须是 1~5，收到 {level}"', 'f"level must be 1~5, got {level}"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有贷款资格，不应进行贷款金额落地"', '"This player is not eligible for a loan and should not proceed with loan amount determination"'),
        ('"该玩家本月没有选择借款，不应进行贷款金额落地"', '"This player did not choose to borrow this month and should not proceed with loan amount determination"'),
        ('description="贷款金额比例题 → 更新 current_loan_amount 写回 player.json"', 'description="Loan amount ratio question -> update current_loan_amount and write back to player.json"'),
        ('"贷款金额比例档位（1=借一点点 … 5=顶格借）"', '"Loan amount ratio level (1=borrow very little ... 5=borrow maximum)"'),
        ('f"档位 {d[\'level\']} → 贷款比例 {d[\'ratio\']*100:.1f}%（占上期工资）→ 贷款金额 {d[\'amount\']:,.0f} 元（已写回 {player_path}）"', 'f"Level {d[\'level\']} -> Loan ratio {d[\'ratio\']*100:.1f}% (of last period wage) -> Loan amount {d[\'amount\']:,.0f} yuan (written back to {player_path})"'),
    ])

    # ===== loan/loan_market_clearing.py =====
    translate_file(os.path.join(BASE, "loan", "loan_market_clearing.py"), [
        ('"conservative": "稳健型"', '"conservative": "conservative"'),
        ('"aggressive": "激进型"', '"aggressive": "aggressive"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"该 agent 没有 tick={t0} 的记录"', 'f"This agent has no record for tick={t0}"'),
        ('f"{bid} 号银行（{label}）"', 'f"Bank #{bid} ({label})"'),
        ('f"{bid} 号银行"', 'f"Bank #{bid}"'),
        ('"【贷款市场 · 撮合结果】"', '"[Loan Market - Matching Results]"'),
        ('description="玩家贷款市场撮合（结果写回 player.json）"', 'description="Player loan market matching (results written back to player.json)"'),
        ('help="results 目录（含 households/firms/banks.json）"', 'help="results directory (containing households/firms/banks.json)"'),
        ('help="可选随机种子（复现）"', 'help="Optional random seed (for reproducibility)"'),
    ])

    # ===== employment/employment_briefing.py =====
    translate_file(os.path.join(BASE, "employment", "employment_briefing.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('"conservative": "保守谨慎"', '"conservative": "conservative and cautious"'),
        ('"steady": "稳健务实"', '"steady": "steady and practical"'),
        ('"balanced": "攻守平衡"', '"balanced": "balanced"'),
        ('"growth": "积极进取"', '"growth": "growth-oriented"'),
        ('"aggressive": "大胆激进"', '"aggressive": "bold and aggressive"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"（你这个角色没有就业决策任务，可以直接跳过人才市场。）"', '"(Your character does not have an employment decision task. You can skip the job market.)"'),
    ])

    # ===== employment/apply_employment_decision.py =====
    translate_file(os.path.join(BASE, "employment", "apply_employment_decision.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('f"wage_level 必须是 1~5，收到 {wage_level}"', 'f"wage_level must be 1~5, got {wage_level}"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有就业决策任务"', '"This player has no employment decision task"'),
        ('"离职"', '"resign"'),
        ('"是"', '"yes"'),
        ('description="就业决策 → 写回 player.json"', 'description="Employment decision -> write back to player.json"'),
        ('help="意愿工资档位"', 'help="Desired wage level"'),
        ('help="是否主动离职：yes/no（失业玩家无此题，可省略）"', 'help="Whether to resign voluntarily: yes/no (unemployed players skip this, optional)"'),
        ('"失业玩家（无离职题，直接进劳动力市场）"', '"Unemployed player (no resignation question, entering labor market directly)"'),
        ('"主动离职"', '"Voluntary resignation"'),
        ('"不离职"', '"Not resigning"'),
        ('"（已置失业，将进劳动力市场）"', '" (set to unemployed, will enter labor market)"'),
        ('"意愿工资档"', '"Desired wage level"'),
        ('"参考工资"', '"Reference wage"'),
        ('"意愿月薪"', '"Desired monthly salary"'),
        ('"元"', '"yuan"'),
    ])

    # ===== employment/labor_market_clearing.py =====
    translate_file(os.path.join(BASE, "employment", "labor_market_clearing.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"该 agent 没有 tick={t0} 的记录"', 'f"This agent has no record for tick={t0}"'),
        ('"【劳动力市场 · 撮合结果】"', '"[Labor Market - Matching Results]"'),
        ('"（你选择不离职，留在了原岗位。）"', '"(You chose not to resign and stayed at your current position.)"'),
        ('"就业状态：在职（选择留任）"', '"Employment status: employed (chose to stay)"'),
        ('"当前雇主：企业"', '"Current employer: Firm"'),
        ('f"当期工资：{wage:,.0f} 元"', 'f"Current wage: {wage:,.0f} yuan"'),
        ('"（非自愿进入市场）"', '" (involuntarily entered the market)"'),
        ('description="玩家劳动力市场撮合（写回 player.json）"', 'description="Player labor market matching (write back to player.json)"'),
    ])

    # ===== consumption/consumption_briefing.py =====
    translate_file(os.path.join(BASE, "consumption", "consumption_briefing.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('"conservative": "保守谨慎"', '"conservative": "conservative and cautious"'),
        ('"steady": "稳健务实"', '"steady": "steady and practical"'),
        ('"balanced": "攻守平衡"', '"balanced": "balanced"'),
        ('"growth": "积极进取"', '"growth": "growth-oriented"'),
        ('"aggressive": "大胆激进"', '"aggressive": "bold and aggressive"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"（你这个角色没有消费决策任务。）"', '"(Your character does not have a consumption decision task.)"'),
    ])

    # ===== consumption/apply_consumption_decision.py =====
    translate_file(os.path.join(BASE, "consumption", "apply_consumption_decision.py"), [
        ('f"档位必须是 1~5，收到 {lv}"', 'f"Level must be 1~5, got {lv}"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有消费决策任务。"', '"This player has no consumption decision task."'),
        ('description="消费四道题 → 写回 player.json"', 'description="Consumption (four questions) -> write back to player.json"'),
        ('"必需品愿价"', '"Necessity bid price"'),
        ('"奢侈品愿价"', '"Luxury bid price"'),
        ('"消费比例"', '"Consumption ratio"'),
        ('"必需品占比"', '"Necessity share"'),
        ('"总预算"', '"Total budget"'),
        ('f" 元（已写回）"', 'f" yuan (written back)"'),
    ])

    # ===== consumption/goods_market_clearing.py =====
    translate_file(os.path.join(BASE, "consumption", "goods_market_clearing.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"该 agent 没有 tick={t0} 的记录"', 'f"This agent has no record for tick={t0}"'),
        ('"【商品市场 · 购物结果】"', '"[Goods Market - Shopping Results]"'),
        ('"（结账后，导购把小票递给你）"', '"(After checkout, the shopping assistant hands you the receipt)"'),
        ('"必需品：买到"', '"Necessities: bought"'),
        ('"件"', '"items"'),
        ('"奢侈品"', '"Luxury goods"'),
        ('"本月消费合计"', '"Total consumption this month"'),
        ('"这个月您几乎没买到东西"', '"You barely bought anything this month"'),
        ('f"消费后您手头还剩约 {remaining:,.0f} 元"', 'f"After spending you have about {remaining:,.0f} yuan left"'),
        ('description="玩家商品市场撮合（写回 player.json）"', 'description="Player goods market matching (write back to player.json)"'),
    ])

    # ===== deposit/deposit_briefing.py =====
    translate_file(os.path.join(BASE, "deposit", "deposit_briefing.py"), [
        ('5: "非常富裕"', '5: "very wealthy"'),
        ('4: "比较宽裕"', '4: "fairly comfortable"'),
        ('3: "不上不下"', '3: "average"'),
        ('2: "手头偏紧"', '2: "somewhat tight"'),
        ('1: "非常拮据"', '1: "very poor"'),
        ('"conservative": "保守谨慎"', '"conservative": "conservative and cautious"'),
        ('"steady": "稳健务实"', '"steady": "steady and practical"'),
        ('"balanced": "攻守平衡"', '"balanced": "balanced"'),
        ('"growth": "积极进取"', '"growth": "growth-oriented"'),
        ('"aggressive": "大胆激进"', '"aggressive": "bold and aggressive"'),
        ('0: "经济有点过热，房地产很火。"', '0: "The economy is slightly overheated, real estate is booming."'),
        ('1: "经济在高位运行，物价开始往上走。"', '1: "The economy is running at a high level, prices are starting to rise."'),
        ('2: "需求还在高位，但势头放缓了。"', '2: "Demand is still high, but momentum is slowing."'),
        ('3: "物价涨得越来越快。"', '3: "Prices are rising faster and faster."'),
        ('4: "涨价压力越来越大。"', '4: "Inflationary pressure is increasing."'),
        ('5: "经济全面过热，物价很高。"', '5: "The economy is fully overheated, prices are very high."'),
        ('6: "物价涨得更凶，通胀在恶化。"', '6: "Prices are surging more fiercely, inflation is worsening."'),
        ("7: \"经济有点'滞胀'，东西贵、大家也开始买不动了。\"", '7: "The economy is showing stagflation signs - things are expensive and people can barely afford to buy."'),
        ('8: "高物价还在持续。"', '8: "High prices persist."'),
        ('9: "经济在降温，但物价还是高。"', '9: "The economy is cooling down, but prices remain high."'),
        ('10: "滞胀加重，需求明显缩水。"', '10: "Stagflation worsens, demand shrinks significantly."'),
        ('11: "物价见顶，但实体经济在走弱。"', '11: "Prices are peaking, but the real economy is weakening."'),
        ('12: "需求全面收缩。"', '12: "Demand is contracting across the board."'),
        ('f"{x:,.0f} 元"', 'f"{x:,.0f} yuan"'),
        ('"未知"', '"unknown"'),
        ('"很强"', '"very strong"'),
        ('"较强"', '"fairly strong"'),
        ('"中等"', '"moderate"'),
        ('"偏弱"', '"somewhat weak"'),
        ('"较弱"', '"fairly weak"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('"（你这个角色没有存款决策任务。）"', '"(Your character does not have a deposit decision task.)"'),
    ])

    # ===== deposit/apply_deposit_decision.py =====
    translate_file(os.path.join(BASE, "deposit", "apply_deposit_decision.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"环境数据里没有 tick={t0} 的记录"', 'f"Environment data has no record for tick={t0}"'),
        ('f"level 必须是 1~5，收到 {level}"', 'f"level must be 1~5, got {level}"'),
        ('f"找不到玩家 JSON：{player_path}"', 'f"Player JSON not found: {player_path}"'),
        ('"该玩家没有存款决策任务。"', '"This player has no deposit decision task."'),
        ('description="意愿存款利率题 → 写回 player.json"', 'description="Desired deposit rate question -> write back to player.json"'),
        ('f"档位 {d[\'level\']} | 上期市场存款利率 {d[\'market_rate\']*100:.2f}% → 意愿存款利率 {d[\'desired_deposit_rate\']*100:.2f}%（已写回）"', 'f"Level {d[\'level\']} | Last period market deposit rate {d[\'market_rate\']*100:.2f}% -> Desired deposit rate {d[\'desired_deposit_rate\']*100:.2f}% (written back)"'),
    ])

    # ===== deposit/deposit_market_clearing.py =====
    translate_file(os.path.join(BASE, "deposit", "deposit_market_clearing.py"), [
        ('"conservative": "稳健型"', '"conservative": "conservative"'),
        ('"aggressive": "激进型"', '"aggressive": "aggressive"'),
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('f"该 agent 没有 tick={t0} 的记录"', 'f"This agent has no record for tick={t0}"'),
        ('"【存款市场 · 结果】\\n\\n（你手头几乎没有剩余资金，这个月没有可存的钱。）"', '"[Deposit Market - Results]\\n\\n(You have almost no remaining funds - there is no money to deposit this month.)"'),
        ('f"{chosen[\'bank_id\']} 号银行（{label}）"', 'f"Bank #{chosen[\'bank_id\']} ({label})"'),
        ('f"{chosen[\'bank_id\']} 号银行"', 'f"Bank #{chosen[\'bank_id\']}"'),
        ('"【存款市场 · 结果】"', '"[Deposit Market - Results]"'),
        ('"（柜员为你办好了存款手续）"', '"(The teller has processed your deposit)"'),
        ('f"「您把剩余的 {amount:,.0f} 元全部存入了{bank_name}，」"', 'f"You deposited all your remaining {amount:,.0f} yuan into {bank_name}. "'),
        ('f"「存款利率 {chosen[\'offered_rate\']*100:.2f}%（按银行报价执行）。本月的所有决策到此就全部完成啦！」"', 'f"Deposit rate: {chosen[\'offered_rate\']*100:.2f}% (executed at bank quoted rate). All decisions for this month are now complete!"'),
        ('description="玩家存款市场撮合（写回 player.json）"', 'description="Player deposit market matching (write back to player.json)"'),
    ])

    # ===== decision_review/decision_review.py =====
    translate_file(os.path.join(BASE, "decision_review", "decision_review.py"), [
        ('("loan", "贷款")', '("loan", "Loan")'),
        ('("employment", "就业")', '("employment", "Employment")'),
        ('("consumption", "消费")', '("consumption", "Consumption")'),
        ('("stock", "股票")', '("stock", "Stock")'),
        ('("deposit", "存款")', '("deposit", "Deposit")'),
        ('"【决策回顾】"', '"[Decision Review]"'),
        ('"（未进行）"', '"(not performed)"'),
        ('"未申请贷款"', '"Did not apply for loan"'),
        ('"成功"', '"Approved"'),
        ('"号银行"', '"Bank #"'),
        ('"申请"', '"Applied"'),
        ('"但未获批"', '"but not approved"'),
        ('"已设定意愿工资（未撮合）"', '"Desired wage set (not yet matched)"'),
        ('"留任"', '"Stayed"'),
        ('"新入职"', '"Newly employed"'),
        ('"（被裁后重新入职）"', '" (re-employed after layoff)"'),
        ('"未匹配到工作，本月失业"', '"No job match, unemployed this month"'),
        ('"（非自愿进入市场）"', '" (involuntarily entered market)"'),
        ('"件（必需品"', '" items (necessities"'),
        ('"+ 奢侈品"', '"+ luxury"'),
        ('"必需品股"', '"Necessity stock"'),
        ('"奢侈品股"', '"Luxury stock"'),
        ('"买入"', '"Bought"'),
        ('"卖出"', '"Sold"'),
        ('"股"', '" shares"'),
        ('"未成交"', '"No transaction"'),
        ('"无可存资金"', '"No funds to deposit"'),
        ('description="决策回顾（输入玩家 JSON）"', 'description="Decision review (input player JSON)"'),
    ])

    # ===== asset_happiness/compare_performance.py =====
    translate_file(os.path.join(BASE, "asset_happiness", "compare_performance.py"), [
        ('f"找不到 JSON 文件：{p}"', 'f"JSON file not found: {p}"'),
        ('description="表现对比：资产变化 & 当期幸福感"', 'description="Performance comparison: asset change & current happiness"'),
        ('"表现对比"', '"Performance Comparison"'),
        ('"对照同组别："', '"Comparison group: "'),
        ('"劳动力"', '"labor force"'),
        ('"非劳动力"', '"non-labor force"'),
        ('"财富档"', '"wealth level"'),
        ('"个 agent"', '" agents"'),
        ('"资产变化："', '"Asset change: "'),
        ('"你"', '"You"'),
        ('"原 Agent"', '"Original Agent"'),
        ('"同组均值"', '"Group average"'),
        ('"当期幸福感："', '"Current happiness: "'),
        ('"分"', '" points"'),
    ])

    print("\n✅ All files translated successfully!")

if __name__ == "__main__":
    main()
